In [18]:
# %%
import json
from pathlib import Path
import pandas as pd

DATA_DIR = Path("../data/datasets/merged_splits")

def load_jsonl(path: Path) -> pd.DataFrame:
    records = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            records.append(json.loads(line))
    return pd.DataFrame(records)

train_df = load_jsonl(DATA_DIR / "train.jsonl")
val_df   = load_jsonl(DATA_DIR / "val.jsonl")
test_df  = load_jsonl(DATA_DIR / "test.jsonl")

for name, df in [("train", train_df), ("val", val_df), ("test", test_df)]:
    print(name, df.shape)


# %%
def show_severity(df, name):
    print(f"\n=== {name.upper()} — severity counts ===")
    print(df["severity"].value_counts(dropna=False))
    print(f"\n=== {name.upper()} — severity proportions ===")
    print(df["severity"].value_counts(normalize=True, dropna=False).round(3))

for name, df in [("train", train_df), ("val", val_df), ("test", test_df)]:
    show_severity(df, name)


# %%
def show_topic(df, name, top_n=20):
    print(f"\n=== {name.upper()} — topic counts (top {top_n}) ===")
    print(df["topic"].value_counts().head(top_n))
    print(f"\n=== {name.upper()} — topic proportions (top {top_n}) ===")
    print(df["topic"].value_counts(normalize=True).head(top_n).round(3))

for name, df in [("train", train_df), ("val", val_df), ("test", test_df)]:
    show_topic(df, name)


# %%
for name, df in [("train", train_df), ("val", val_df), ("test", test_df)]:
    print(f"\n=== {name.upper()} — source counts ===")
    print(df["source"].value_counts())
    print(f"\n=== {name.upper()} — source proportions ===")
    print(df["source"].value_counts(normalize=True).round(3))

train (5414, 7)
val (675, 7)
test (679, 7)

=== TRAIN — severity counts ===
severity
green     4159
yellow    1208
red         47
Name: count, dtype: int64

=== TRAIN — severity proportions ===
severity
green     0.768
yellow    0.223
red       0.009
Name: proportion, dtype: float64

=== VAL — severity counts ===
severity
green     509
yellow    160
red         6
Name: count, dtype: int64

=== VAL — severity proportions ===
severity
green     0.754
yellow    0.237
red       0.009
Name: proportion, dtype: float64

=== TEST — severity counts ===
severity
green     523
yellow    150
red         6
Name: count, dtype: int64

=== TEST — severity proportions ===
severity
green     0.770
yellow    0.221
red       0.009
Name: proportion, dtype: float64

=== TRAIN — topic counts (top 20) ===
topic
feeding          1016
breastfeeding     571
sleep             191
pumping            93
support            88
development        83
safety             73
weaning            66
therapy            60
behavior           59
parenting          41
pediatrician       40
nutrition          40
growth             39
postpartum         38
soothing           33
discipline         33
vision             31
immunizations      30
nursing            29
Name: count, dtype: int64

=== TRAIN — topic proportions (top 20) ===
topic
feeding          0.188
breastfeeding    0.105
sleep            0.035
pumping          0.017
support          0.016
development      0.015
safety           0.013
weaning          0.012
therapy          0.011
behavior         0.011
parenting        0.008
pediatrician     0.007
nutrition        0.007
growth           0.007
postpartum       0.007
soothing         0.006
discipline       0.006
vision           0.006
immunizations    0.006
nursing          0.005
Name: proportion, dtype: float64

=== VAL — topic counts (top 20) ===
topic
feeding                  121
breastfeeding             62
sleep                     16
development               12
support                    9
growth                     7
pumping                    7
safety                     7
postpartum depression      6
newborn                    6
pediatrician               6
weaning                    5
nutrition                  5
behavior                   5
mastitis                   5
SIDS                       5
labor                      4
bowel movements            4
parenting                  4
newborn care               4
Name: count, dtype: int64

=== VAL — topic proportions (top 20) ===
topic
feeding                  0.179
breastfeeding            0.092
sleep                    0.024
development              0.018
support                  0.013
growth                   0.010
pumping                  0.010
safety                   0.010
postpartum depression    0.009
newborn                  0.009
pediatrician             0.009
weaning                  0.007
nutrition                0.007
behavior                 0.007
mastitis                 0.007
SIDS                     0.007
labor                    0.006
bowel movements          0.006
parenting                0.006
newborn care             0.006
Name: proportion, dtype: float64

=== TEST — topic counts (top 20) ===
topic
feeding                  129
breastfeeding             65
development               16
sleep                     16
support                   12
safety                    12
weaning                   12
behavior                  10
bonding                    7
pumping                    6
immunizations              5
nursing                    5
therapy                    5
bathing                    5
postpartum                 5
induced lactation          5
soothing                   5
postpartum depression      4
supplements                4
bowel movements            4
Name: count, dtype: int64

=== TEST — topic proportions (top 20) ===
topic
feeding                  0.190
breastfeeding            0.096
development              0.024
sleep                    0.024
support                  0.018
safety                   0.018
weaning                  0.018
behavior                 0.015
bonding                  0.010
pumping                  0.009
immunizations            0.007
nursing                  0.007
therapy                  0.007
bathing                  0.007
postpartum               0.007
induced lactation        0.007
soothing                 0.007
postpartum depression    0.006
supplements              0.006
bowel movements          0.006
Name: proportion, dtype: float64

=== TRAIN — source counts ===
source
womanly_art_breastfeeding    3059
caring_baby_young_child      2052
therapy_postpartum_woman      303
Name: count, dtype: int64

=== TRAIN — source proportions ===
source
womanly_art_breastfeeding    0.565
caring_baby_young_child      0.379
therapy_postpartum_woman     0.056
Name: proportion, dtype: float64

=== VAL — source counts ===
source
womanly_art_breastfeeding    382
caring_baby_young_child      256
therapy_postpartum_woman      37
Name: count, dtype: int64

=== VAL — source proportions ===
source
womanly_art_breastfeeding    0.566
caring_baby_young_child      0.379
therapy_postpartum_woman     0.055
Name: proportion, dtype: float64

=== TEST — source counts ===
source
womanly_art_breastfeeding    383
caring_baby_young_child      257
therapy_postpartum_woman      39
Name: count, dtype: int64

=== TEST — source proportions ===
source
womanly_art_breastfeeding    0.564
caring_baby_young_child      0.378
therapy_postpartum_woman     0.057
Name: proportion, dtype: float64

In [7]:
def show_severity(df, name):
    print(f"\n=== {name.upper()} — severity counts ===")
    print(df["severity"].value_counts(dropna=False))
    print("\n=== {name.upper()} — severity proportions ===")
    print(df["severity"].value_counts(normalize=True, dropna=False).round(3))

for name, df in [("train", train_df), ("val", val_df), ("test", test_df)]:
    show_severity(df, name)

=== TRAIN — severity counts ===
severity
green     4159
yellow    1208
red         47
Name: count, dtype: int64

=== {name.upper()} — severity proportions ===
severity
green     0.768
yellow    0.223
red       0.009
Name: proportion, dtype: float64

=== VAL — severity counts ===
severity
green     509
yellow    160
red         6
Name: count, dtype: int64

=== {name.upper()} — severity proportions ===
severity
green     0.754
yellow    0.237
red       0.009
Name: proportion, dtype: float64

=== TEST — severity counts ===
severity
green     523
yellow    150
red         6
Name: count, dtype: int64

=== {name.upper()} — severity proportions ===
severity
green     0.770
yellow    0.221
red       0.009
Name: proportion, dtype: float64

In [8]:
def show_topic(df, name, top_n=20):
    print(f"\n=== {name.upper()} — topic counts (top {top_n}) ===")
    print(df["topic"].value_counts().head(top_n))
    print("\n=== {name.upper()} — topic proportions (top {top_n}) ===")
    print(df["topic"].value_counts(normalize=True).head(top_n).round(3))

for name, df in [("train", train_df), ("val", val_df), ("test", test_df)]:
    show_topic(df, name)

=== TRAIN — topic counts (top 20) ===
topic
feeding          1016
breastfeeding     571
sleep             191
pumping            93
support            88
development        83
safety             73
weaning            66
therapy            60
behavior           59
parenting          41
pediatrician       40
nutrition          40
growth             39
postpartum         38
soothing           33
discipline         33
vision             31
immunizations      30
nursing            29
Name: count, dtype: int64

=== {name.upper()} — topic proportions (top {top_n}) ===
topic
feeding          0.188
breastfeeding    0.105
sleep            0.035
pumping          0.017
support          0.016
development      0.015
safety           0.013
weaning          0.012
therapy          0.011
behavior         0.011
parenting        0.008
pediatrician     0.007
nutrition        0.007
growth           0.007
postpartum       0.007
soothing         0.006
discipline       0.006
vision           0.006
immunizations    0.006
nursing          0.005
Name: proportion, dtype: float64

=== VAL — topic counts (top 20) ===
topic
feeding                  121
breastfeeding             62
sleep                     16
development               12
support                    9
growth                     7
pumping                    7
safety                     7
postpartum depression      6
newborn                    6
pediatrician               6
weaning                    5
nutrition                  5
behavior                   5
mastitis                   5
SIDS                       5
labor                      4
bowel movements            4
parenting                  4
newborn care               4
Name: count, dtype: int64

=== {name.upper()} — topic proportions (top {top_n}) ===
topic
feeding                  0.179
breastfeeding            0.092
sleep                    0.024
development              0.018
support                  0.013
growth                   0.010
pumping                  0.010
safety                   0.010
postpartum depression    0.009
newborn                  0.009
pediatrician             0.009
weaning                  0.007
nutrition                0.007
behavior                 0.007
mastitis                 0.007
SIDS                     0.007
labor                    0.006
bowel movements          0.006
parenting                0.006
newborn care             0.006
Name: proportion, dtype: float64

=== TEST — topic counts (top 20) ===
topic
feeding                  129
breastfeeding             65
development               16
sleep                     16
support                   12
safety                    12
weaning                   12
behavior                  10
bonding                    7
pumping                    6
immunizations              5
nursing                    5
therapy                    5
bathing                    5
postpartum                 5
induced lactation          5
soothing                   5
postpartum depression      4
supplements                4
bowel movements            4
Name: count, dtype: int64

=== {name.upper()} — topic proportions (top {top_n}) ===
topic
feeding                  0.190
breastfeeding            0.096
development              0.024
sleep                    0.024
support                  0.018
safety                   0.018
weaning                  0.018
behavior                 0.015
bonding                  0.010
pumping                  0.009
immunizations            0.007
nursing                  0.007
therapy                  0.007
bathing                  0.007
postpartum               0.007
induced lactation        0.007
soothing                 0.007
postpartum depression    0.006
supplements              0.006
bowel movements          0.006
Name: proportion, dtype: float64

In [9]:
for name, df in [("train", train_df), ("val", val_df), ("test", test_df)]:
    print(f"\n=== {name.upper()} — source counts ===")
    print(df["source"].value_counts())
    print(f"\n=== {name.upper()} — source proportions ===")
    print(df["source"].value_counts(normalize=True).round(3))

=== TRAIN — source counts ===
source
womanly_art_breastfeeding    3059
caring_baby_young_child      2052
therapy_postpartum_woman      303
Name: count, dtype: int64

=== TRAIN — source proportions ===
source
womanly_art_breastfeeding    0.565
caring_baby_young_child      0.379
therapy_postpartum_woman     0.056
Name: proportion, dtype: float64

=== VAL — source counts ===
source
womanly_art_breastfeeding    382
caring_baby_young_child      256
therapy_postpartum_woman      37
Name: count, dtype: int64

=== VAL — source proportions ===
source
womanly_art_breastfeeding    0.566
caring_baby_young_child      0.379
therapy_postpartum_woman     0.055
Name: proportion, dtype: float64

=== TEST — source counts ===
source
womanly_art_breastfeeding    383
caring_baby_young_child      257
therapy_postpartum_woman      39
Name: count, dtype: int64

=== TEST — source proportions ===
source
womanly_art_breastfeeding    0.564
caring_baby_young_child      0.378
therapy_postpartum_woman     0.057
Name: proportion, dtype: float64

In [10]:
# %%
# Summary table: severity distribution by split (counts + percentages)

def severity_summary_table(train_df, val_df, test_df):
    rows = []
    for name, df in [("train", train_df), ("val", val_df), ("test", test_df)]:
        n = len(df)
        counts = df["severity"].value_counts(dropna=False)
        props = df["severity"].value_counts(normalize=True, dropna=False)

        for sev in sorted(counts.index):
            rows.append(
                {
                    "split": name,
                    "severity": sev,
                    "count": counts[sev],
                    "percent": round(props[sev] * 100, 1),
                    "n_split": n,
                }
            )
    return pd.DataFrame(rows)

sev_summary_df = severity_summary_table(train_df, val_df, test_df)
sev_summary_df

   split severity  count  percent  n_split
0  train    green   4159     76.8     5414
1  train      red     47      0.9     5414
2  train   yellow   1208     22.3     5414
3    val    green    509     75.4      675
4    val      red      6      0.9      675
5    val   yellow    160     23.7      675
6   test    green    523     77.0      679
7   test      red      6      0.9      679
8   test   yellow    150     22.1      679

In [12]:
# %%
# Summary table: top topics per split

def topic_summary_table(train_df, val_df, test_df, top_n=15):
    rows = []
    for name, df in [("train", train_df), ("val", val_df), ("test", test_df)]:
        counts = df["topic"].value_counts().head(top_n)
        props = df["topic"].value_counts(normalize=True).head(top_n)

        for topic in counts.index:
            rows.append(
                {
                    "split": name,
                    "topic": topic,
                    "count": counts[topic],
                    "percent": round(props[topic] * 100, 1),
                }
            )
    return pd.DataFrame(rows)

topic_summary_df = topic_summary_table(train_df, val_df, test_df, top_n=15)
topic_summary_df

    split                  topic  count  percent
0   train                feeding   1016     18.8
1   train          breastfeeding    571     10.5
2   train                  sleep    191      3.5
3   train                pumping     93      1.7
4   train                support     88      1.6
5   train            development     83      1.5
6   train                 safety     73      1.3
7   train                weaning     66      1.2
8   train                therapy     60      1.1
9   train               behavior     59      1.1
10  train              parenting     41      0.8
11  train           pediatrician     40      0.7
12  train              nutrition     40      0.7
13  train                 growth     39      0.7
14  train             postpartum     38      0.7
15    val                feeding    121     17.9
16    val          breastfeeding     62      9.2
17    val                  sleep     16      2.4
18    val            development     12      1.8
19    val                support      9      1.3
20    val                 growth      7      1.0
21    val                pumping      7      1.0
22    val                 safety      7      1.0
23    val  postpartum depression      6      0.9
24    val                newborn      6      0.9
25    val           pediatrician      6      0.9
26    val                weaning      5      0.7
27    val              nutrition      5      0.7
28    val               behavior      5      0.7
29    val               mastitis      5      0.7
30   test                feeding    129     19.0
31   test          breastfeeding     65      9.6
32   test            development     16      2.4
33   test                  sleep     16      2.4
34   test                support     12      1.8
35   test                 safety     12      1.8
36   test                weaning     12      1.8
37   test               behavior     10      1.5
38   test                bonding      7      1.0
39   test                pumping      6      0.9
40   test          immunizations      5      0.7
41   test                nursing      5      0.7
42   test                therapy      5      0.7
43   test                bathing      5      0.7
44   test             postpartum      5      0.7

In [20]:
# %%
# Source distribution by split

def source_summary_table(train_df, val_df, test_df):
    rows = []
    for name, df in [("train", train_df), ("val", val_df), ("test", test_df)]:
        n = len(df)
        counts = df["source"].value_counts()
        props = df["source"].value_counts(normalize=True)

        for src in counts.index:
            rows.append(
                {
                    "split": name,
                    "source": src,
                    "count": counts[src],
                    "percent": round(props[src] * 100, 1),
                    "n_split": n,
                }
            )
    return pd.DataFrame(rows)

source_summary_df = source_summary_table(train_df, val_df, test_df)
source_summary_df

   split                     source  count  percent  n_split
0  train  womanly_art_breastfeeding   3059     56.5     5414
1  train    caring_baby_young_child   2052     37.9     5414
2  train   therapy_postpartum_woman    303      5.6     5414
3    val  womanly_art_breastfeeding    382     56.6      675
4    val    caring_baby_young_child    256     37.9      675
5    val   therapy_postpartum_woman     37      5.5      675
6   test  womanly_art_breastfeeding    383     56.4      679
7   test    caring_baby_young_child    257     37.8      679
8   test   therapy_postpartum_woman     39      5.7      679

In [21]:
df# %%
def length_stats(df, name):
    texts = df["output"]
    char_lens = texts.str.len()
    token_lens = texts.str.split().apply(len)

    return {
        "split": name,
        "n": len(df),
        "mean_chars": char_lens.mean(),
        "median_chars": char_lens.median(),
        "mean_tokens": token_lens.mean(),
        "median_tokens": token_lens.median(),
    }

length_rows = []
for name, df in [("train", train_df), ("val", val_df), ("test", test_df)]:
    length_rows.append(length_stats(df, name))

length_stats_df = pd.DataFrame(length_rows).round(1)
length_stats_df

   split     n  mean_chars  median_chars  mean_tokens  median_tokens
0  train  5414       229.9         211.0         38.2           35.0
1    val   675       232.3         216.0         38.4           36.0
2   test   679       226.1         213.0         37.4           35.0

In [22]:
# %%
for name, df in [("train", train_df), ("val", val_df), ("test", test_df)]:
    non_empty = df["input"].fillna("").str.strip().ne("").sum()
    print(f"{name}: non-empty input = {non_empty} / {len(df)}")

train: non-empty input = 0 / 5414
val: non-empty input = 0 / 675
test: non-empty input = 0 / 679